const Slogans = [
        'The little coffee shop on the corner of the street.',
        'Dive into the world of comfort.',
        'Your daily happiness.',
        'Coffee is Your Friend.',
        "Coffee so good, it is worth a selfie.",
        'We like you, come on in.',
        'A coffee shop for the rest of us.',
        "You have got a friend in coffee.",
        "You are here. You are good.",
        'The best part of waking up is coffee.',
        'Make coffee not war.',
        'Home of the original latte art.',
        'A cup of happiness.',
        'Good coffee, Good times.',
        'You will be smiling all day!',
        'Come in and stay awhile.',
        'Coffee, Coffee, Coffee!',
        'The coffee shop of your dreams.',
        'Coffee is forever.',
        'Living the dream!',
        'Sip, chat, share, relax.',
        'Where coffee and community come together.',
        'Our passion is in our coffee.',
        'Where friends meet, memories happen.',
        'This is one of the most important things you do today.',
        'Exchange cultural experiences over coffee.',
        'Coffee, Inspiration, Passion.',
        'Coffee made with care.',
        'Coffee so good you will never want to leave.',
        'A great cup of coffee. And then another.'
    ]

    export default Slogans;